version: '3.3'
services:
  php:
    build: .
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      backend:
        aliases: 
          - news-php

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
        - .:/code
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - backend
    ports:
    - "80:80"
    depends_on:
        - php

  mysql8:
    image: mysql:8.0
    command: --sort_buffer_size=512K
    container_name: mysql_8
    restart: unless-stopped
    volumes:
      - db-data-mysql8:/var/lib/mysql
      - ./shared/:/home/shared
    networks:
      backend:
        aliases:
          - mysql8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}


networks:
  backend:
  
volumes:
  db-data-mysql8: